/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.GUI;

import javax.swing.JOptionPane;
import edu.esprit.DAO.AdminDAO;
import edu.esprit.entities.Admin;
import edu.esprit.util.Controle;

/**
 *
 * @author Abd
 */
public class Ajoutadmin extends javax.swing.JDialog {

    /**
     * Creates new form Ajoutadmin
     */
    public Ajoutadmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        nnnom.setVisible(false);
        nnprnom.setVisible(false);
        nnlogin.setVisible(false);
        nnmdp.setVisible(false);
        nnmail.setVisible(false);

       
        oknom.setVisible(false);
        okprnm.setVisible(false);
        oklogin.setVisible(false);
        okmdp.setVisible(false);
        okmail.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnom = new java.awt.TextField();
        txtprenom = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtlogin = new javax.swing.JTextField();
        txtmdp = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnajout = new javax.swing.JButton();
        btnreinit = new javax.swing.JButton();
        btnquit = new javax.swing.JButton();
        nnnom = new javax.swing.JLabel();
        oknom = new javax.swing.JLabel();
        okprnm = new javax.swing.JLabel();
        nnprnom = new javax.swing.JLabel();
        nnmdp = new javax.swing.JLabel();
        okmdp = new javax.swing.JLabel();
        oklogin = new javax.swing.JLabel();
        nnlogin = new javax.swing.JLabel();
        nnmail = new javax.swing.JLabel();
        okmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Nom:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel2.setText("Prenom:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel3.setText("Email:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel4.setText("Login");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 215, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel5.setText("Mot de passe");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 266, -1, -1));

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomKeyPressed(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 49, 194, -1));

        txtprenom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprenomKeyTyped(evt);
            }
        });
        getContentPane().add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 106, 194, -1));

        txtmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmailKeyTyped(evt);
            }
        });
        getContentPane().add(txtmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 194, -1));

        txtlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtloginKeyTyped(evt);
            }
        });
        getContentPane().add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 219, 194, -1));

        txtmdp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmdpKeyTyped(evt);
            }
        });
        getContentPane().add(txtmdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 194, -1));

        btnajout.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnajout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1393447771_plus-24.png"))); // NOI18N
        btnajout.setText("Ajouter");
        btnajout.setToolTipText("");
        btnajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajoutActionPerformed(evt);
            }
        });

        btnreinit.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnreinit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1393447351_erase.png"))); // NOI18N
        btnreinit.setText("Reinitialiser");
        btnreinit.setMaximumSize(new java.awt.Dimension(121, 41));
        btnreinit.setPreferredSize(new java.awt.Dimension(121, 41));
        btnreinit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreinitActionPerformed(evt);
            }
        });

        btnquit.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnquit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1393447726_cross-24.png"))); // NOI18N
        btnquit.setText("Quitter");
        btnquit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnreinit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnajout)
                .addGap(27, 27, 27)
                .addComponent(btnquit)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnajout)
                    .addComponent(btnreinit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnquit))
                .addGap(19, 19, 19))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 376, -1, -1));

        nnnom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        getContentPane().add(nnnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        oknom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accept.png"))); // NOI18N
        getContentPane().add(oknom, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        okprnm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accept.png"))); // NOI18N
        getContentPane().add(okprnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        nnprnom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        getContentPane().add(nnprnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        nnmdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        getContentPane().add(nnmdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        okmdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accept.png"))); // NOI18N
        getContentPane().add(okmdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        oklogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accept.png"))); // NOI18N
        getContentPane().add(oklogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        nnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        getContentPane().add(nnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        nnmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N
        getContentPane().add(nnmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        okmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accept.png"))); // NOI18N
        getContentPane().add(okmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void btnreinitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreinitActionPerformed
        // TODO add your handling code here:
        txtlogin.setText("");
        txtnom.setText("");
        txtprenom.setText("");
        txtmail.setText("");
        txtmdp.setText("");
        nnnom.setVisible(false);
        nnprnom.setVisible(false);
        nnlogin.setVisible(false);
        nnmdp.setVisible(false);
        nnmail.setVisible(false);

       
        oknom.setVisible(false);
        okprnm.setVisible(false);
        oklogin.setVisible(false);
        okmdp.setVisible(false);
        okmail.setVisible(false);
        
    }//GEN-LAST:event_btnreinitActionPerformed

    private void btnajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajoutActionPerformed
        // TODO add your handling code here:
        Admin ad = new Admin();
        AdminDAO adminDAO = new AdminDAO();
       

        if ((nom == false) || (prenom == false) || (email == false) || (login == false) || (mdp == false)) {
            jperr.showMessageDialog(this, "Certaines données saisies sont invalides", "Erreur", jperr.ERROR_MESSAGE);
        
        }
       else if((txtnom==null)||(txtprenom==null)||(txtlogin==null)||(txtmdp==null)||(txtmail==null))
        {jperr.showMessageDialog(this, "Certaines données saisies sont invalides", "Erreur", jperr.ERROR_MESSAGE);}
        else {
            ad.setNom(txtnom.getText());
            ad.setPrenom(txtprenom.getText());
            ad.setEmail(txtmail.getText());
            ad.setLogin(txtlogin.getText());
            ad.setMdp(txtmdp.getText());
            adminDAO.insertAdmin(ad);
            jperr.showMessageDialog(this, "Ajout Réussi", "Element Ajouté", jperr.INFORMATION_MESSAGE);
            nnnom.setVisible(false);
        nnprnom.setVisible(false);
        nnlogin.setVisible(false);
        nnmdp.setVisible(false);
        nnmail.setVisible(false);

       
        oknom.setVisible(false);
        okprnm.setVisible(false);
        oklogin.setVisible(false);
        okmdp.setVisible(false);
        okmail.setVisible(false);
            
        

    }                               
    }//GEN-LAST:event_btnajoutActionPerformed

    private void txtnomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyPressed
        // TODO add your handling code here:
        
        Controle c = new Controle();
        boolean result = c.controlestring(txtnom.getText());
        System.out.println("" + result);
        if (result == true) {
            nom = true;
            oknom.setVisible(true);
            nnnom.setVisible(false);
        } else if (result == false) {
            nom = false;
            oknom.setVisible(false);
            nnnom.setVisible(true);
        } else if (txtnom.getText() == null) {
            nom = false;
            oknom.setVisible(false);
            nnnom.setVisible(true);
        }
        
    }//GEN-LAST:event_txtnomKeyPressed

    private void txtprenomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprenomKeyTyped
        // TODO add your handling code here:
        Controle c = new Controle();
        boolean result = c.controlestring(txtprenom.getText());
        System.out.println("" + result);
        if (result == true) {
            prenom = true;
            okprnm.setVisible(true);
            nnprnom.setVisible(false);
        } else if (result == false) {
            prenom = false;
            okprnm.setVisible(false);
            nnprnom.setVisible(true);
        } else if (txtprenom.getText() == null) {
            prenom = false;
            okprnm.setVisible(false);
            nnprnom.setVisible(true);
        }
        
    }//GEN-LAST:event_txtprenomKeyTyped

    private void txtmdpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmdpKeyTyped
   
        // TODO add your handling code here:
        Controle c = new Controle();
        boolean result = c.controlelogin(txtmdp.getText());
        System.out.println("" + result);
        if (result == true) {
            mdp = true;
            okmdp.setVisible(true);
            nnmdp.setVisible(false);
        } else if (result == false) {
            mdp = false;
            okmdp.setVisible(false);
            nnmdp.setVisible(true);
        } else if (txtmdp.getText() == null) {
            mdp = false;
            okmdp.setVisible(false);
            nnmdp.setVisible(true);
        }
        
        
    }//GEN-LAST:event_txtmdpKeyTyped

    private void txtloginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtloginKeyTyped
    
        // TODO add your handling code here:
        
        
        Controle c = new Controle();
        boolean result = c.controlelogin(txtlogin.getText());
        System.out.println("" + result);
        if (result == true) {
            login = true;
            oklogin.setVisible(true);
            nnlogin.setVisible(false);
        } else if (result == false) {
            login = false;
            oklogin.setVisible(false);
            nnlogin.setVisible(true);
        } else if (txtlogin.getText() == null) {
            login = false;
            oklogin.setVisible(false);
            nnlogin.setVisible(true);
        }
        
        
    }//GEN-LAST:event_txtloginKeyTyped

    private void txtmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmailKeyTyped
        // TODO add your handling code here:
        
        
        Controle c = new Controle();
        boolean result = c.controlemail(txtmail.getText());
        if (result == true) {
            email = true;
            okmail.setVisible(true);
            nnmail.setVisible(false);
        } else if (result == false) {
            email = false;
            okmail.setVisible(false);
            nnmail.setVisible(true);
        } else if (txtmail.getText() == null) {
            email = false;
            okmail.setVisible(false);
            nnmail.setVisible(true);
        }
    }//GEN-LAST:event_txtmailKeyTyped

    private void btnquitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquitActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_btnquitActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajoutadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajoutadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajoutadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajoutadmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ajoutadmin dialog = new Ajoutadmin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajout;
    private javax.swing.JButton btnquit;
    private javax.swing.JButton btnreinit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nnlogin;
    private javax.swing.JLabel nnmail;
    private javax.swing.JLabel nnmdp;
    private javax.swing.JLabel nnnom;
    private javax.swing.JLabel nnprnom;
    private javax.swing.JLabel oklogin;
    private javax.swing.JLabel okmail;
    private javax.swing.JLabel okmdp;
    private javax.swing.JLabel oknom;
    private javax.swing.JLabel okprnm;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmdp;
    private java.awt.TextField txtnom;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
private javax.swing.JOptionPane jperr;
    public boolean nom = true;
    public boolean prenom = true;
    public boolean mdp = true;
    public boolean login = true;
    public boolean email = true;
    

}
