/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.esprit.GUI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import edu.esprit.util.MyConnection;

/**
 *
 * @author Majdi Chaabene
 */
public class ClientAcceuilService extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pre = null;

    /**
     * Creates new form AcceuilServiceClient
     */
    public ClientAcceuilService() {
        initComponents();
        try {
            con = MyConnection.getInstance();
        } catch (SQLException ex) {
            Logger.getLogger(ClientAcceuilService.class.getName()).log(Level.SEVERE, null, ex);
        }
        Update();
        Fillcombo();
    }

    public void Update() {
        try {
            String sql;
            sql = "select id_Service,Lieux,Type,Infos,Prix from services";
            pre = con.prepareStatement(sql);
            rs = pre.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    private void Fillcombo() {
        try {
            String sql = "select distinct Lieux from services";
            pre = con.prepareStatement(sql);
            rs = pre.executeQuery();
            while (rs.next()) {
                String lieux = rs.getString("Lieux");
                lieuxcombo.addItem(lieux);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelclientacceuilservice = new javax.swing.JPanel();
        slideprix = new javax.swing.JSlider();
        recherche = new javax.swing.JButton();
        radiopension = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        inscrire = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lieuxcombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        radiotoilettage = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        slideprix.setMajorTickSpacing(20);
        slideprix.setPaintLabels(true);
        slideprix.setPaintTicks(true);

        recherche.setText("Recherche");
        recherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiopension);
        radiopension.setText("Pension");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        inscrire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/esprit/GUI/1393482476_write_square_black.png"))); // NOI18N
        inscrire.setText("S'inscrire");
        inscrire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscrireActionPerformed(evt);
            }
        });

        jButton1.setText("Liste des sercices");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lieuxcombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choix du Lieux" }));
        lieuxcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lieuxcomboActionPerformed(evt);
            }
        });

        jLabel3.setText("Prix");

        buttonGroup1.add(radiotoilettage);
        radiotoilettage.setText("Toilettage");

        jLabel2.setText("Type");

        jLabel1.setText("Lieux");

        javax.swing.GroupLayout panelclientacceuilserviceLayout = new javax.swing.GroupLayout(panelclientacceuilservice);
        panelclientacceuilservice.setLayout(panelclientacceuilserviceLayout);
        panelclientacceuilserviceLayout.setHorizontalGroup(
            panelclientacceuilserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelclientacceuilserviceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelclientacceuilserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelclientacceuilserviceLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelclientacceuilserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelclientacceuilserviceLayout.createSequentialGroup()
                                .addGroup(panelclientacceuilserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(panelclientacceuilserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiotoilettage)
                                    .addComponent(lieuxcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radiopension)))
                            .addGroup(panelclientacceuilserviceLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(slideprix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(recherche)))
                    .addGroup(panelclientacceuilserviceLayout.createSequentialGroup()
                        .addComponent(inscrire)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        panelclientacceuilserviceLayout.setVerticalGroup(
            panelclientacceuilserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelclientacceuilserviceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelclientacceuilserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelclientacceuilserviceLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(panelclientacceuilserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lieuxcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelclientacceuilserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(radiopension))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiotoilettage)
                        .addGap(18, 18, 18)
                        .addGroup(panelclientacceuilserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(slideprix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(recherche)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelclientacceuilserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inscrire)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelclientacceuilservice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelclientacceuilservice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lieuxcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lieuxcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lieuxcomboActionPerformed

    private void rechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheActionPerformed
        int a1 = slideprix.getValue();

        String a3 = lieuxcombo.getSelectedItem().toString();
        String a4;
        if (radiopension.isSelected()) {
            a4 = "pension";
        } else {
            a4 = "toilettage";
        }
        try {
            String sql1;
            sql1 = "select Lieux,Type,Infos,Prix from services where (Prix <=" + a1 + " AND Type='" + a4 + "' AND Lieux='" + a3 + "' )";

            pre = con.prepareStatement(sql1);
            rs = pre.executeQuery();
            table.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new ClientListeDesServices().setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inscrireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscrireActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Voulez vous vraiment s'inscrire a ce service","Vérification", JOptionPane.YES_NO_OPTION);
        if (p == 0) {
            int row = table.getSelectedRow();
            int a=3;
            String tableclick = (table.getModel().getValueAt(row, 0).toString());
            String sql = "insert into inscription  set id_Client='"+a+"',id_Service='" + tableclick + "' ";
            try {
                pre = con.prepareStatement(sql);
                pre.execute();
                JOptionPane.showMessageDialog(null, "Vous étes désormé inscrit a ce service :)");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_inscrireActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientAcceuilService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientAcceuilService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientAcceuilService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientAcceuilService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientAcceuilService().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton inscrire;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox lieuxcombo;
    private javax.swing.JPanel panelclientacceuilservice;
    private javax.swing.JRadioButton radiopension;
    private javax.swing.JRadioButton radiotoilettage;
    private javax.swing.JButton recherche;
    private javax.swing.JSlider slideprix;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
