/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.GUI;
import edu.esprit.panel.ADMIN_paneladminprincipal;
import edu.esprit.panel.ADMIN_paneladminprincipal;
import edu.esprit.panel.ADMIN_panelclientprincipale;

/**
 *
 * @author Abd
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuAdmin() {
        initComponents();
        pacontenu.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        pacontenu = new javax.swing.JPanel();
        paadmin = new javax.swing.JPanel();
        paclients = new javax.swing.JPanel();
        paservice = new javax.swing.JPanel();
        paanimaux = new javax.swing.JPanel();
        paexpert = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pacontenu.setLayout(new java.awt.CardLayout());

        paadmin.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout paadminLayout = new javax.swing.GroupLayout(paadmin);
        paadmin.setLayout(paadminLayout);
        paadminLayout.setHorizontalGroup(
            paadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        paadminLayout.setVerticalGroup(
            paadminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pacontenu.add(paadmin, "card2");

        paclients.setBackground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout paclientsLayout = new javax.swing.GroupLayout(paclients);
        paclients.setLayout(paclientsLayout);
        paclientsLayout.setHorizontalGroup(
            paclientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        paclientsLayout.setVerticalGroup(
            paclientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pacontenu.add(paclients, "card2");

        paservice.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout paserviceLayout = new javax.swing.GroupLayout(paservice);
        paservice.setLayout(paserviceLayout);
        paserviceLayout.setHorizontalGroup(
            paserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        paserviceLayout.setVerticalGroup(
            paserviceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pacontenu.add(paservice, "card2");

        paanimaux.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout paanimauxLayout = new javax.swing.GroupLayout(paanimaux);
        paanimaux.setLayout(paanimauxLayout);
        paanimauxLayout.setHorizontalGroup(
            paanimauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        paanimauxLayout.setVerticalGroup(
            paanimauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pacontenu.add(paanimaux, "card2");

        paexpert.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout paexpertLayout = new javax.swing.GroupLayout(paexpert);
        paexpert.setLayout(paexpertLayout);
        paexpertLayout.setHorizontalGroup(
            paexpertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 745, Short.MAX_VALUE)
        );
        paexpertLayout.setVerticalGroup(
            paexpertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pacontenu.add(paexpert, "card2");

        jMenuBar1.setPreferredSize(new java.awt.Dimension(279, 50));

        jMenu1.setText("Administrateur");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Clients");
        jMenu2.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu2MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu5.setText("Expert");
        jMenu5.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu5MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu3.setText("Services");
        jMenu3.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu3MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Animaux");
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pacontenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pacontenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        // TODO add your handling code here:
        ADMIN_paneladminprincipal c=new ADMIN_paneladminprincipal();
        pacontenu.setVisible(true);
        pacontenu.removeAll();
        pacontenu.add(c);
        pacontenu.repaint();
        pacontenu.revalidate();
    }//GEN-LAST:event_jMenu1MenuSelected

    private void jMenu2MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu2MenuSelected
        // TODO add your handling code here:
        ADMIN_panelclientprincipale p=new ADMIN_panelclientprincipale();
        pacontenu.setVisible(true);
        pacontenu.removeAll();
        pacontenu.add(p);
        pacontenu.repaint();
        pacontenu.revalidate();
    }//GEN-LAST:event_jMenu2MenuSelected

    private void jMenu5MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu5MenuSelected
        // TODO add your handling code here:
        pacontenu.setVisible(true);
        pacontenu.removeAll();
        pacontenu.add(paexpert);
        pacontenu.repaint();
        pacontenu.revalidate();
    }//GEN-LAST:event_jMenu5MenuSelected

    private void jMenu3MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu3MenuSelected
        // TODO add your handling code here:
        pacontenu.setVisible(true);
        pacontenu.removeAll();
        pacontenu.add(paservice);
        pacontenu.repaint();
        pacontenu.revalidate();
    }//GEN-LAST:event_jMenu3MenuSelected

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
        // TODO add your handling code here:
        pacontenu.setVisible(true);
        pacontenu.removeAll();
        pacontenu.add(paanimaux);
        pacontenu.repaint();
        pacontenu.revalidate();
    }//GEN-LAST:event_jMenu4MenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel paadmin;
    private javax.swing.JPanel paanimaux;
    private javax.swing.JPanel paclients;
    private javax.swing.JPanel pacontenu;
    private javax.swing.JPanel paexpert;
    private javax.swing.JPanel paservice;
    // End of variables declaration//GEN-END:variables
}
