/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.esprit.panel;

import edu.esprit.DAO.AdminDAO;
import edu.esprit.GUI.AdminAffichertout;
import edu.esprit.GUI.Ajoutadmin;
import edu.esprit.GUI.MenuAdmin;
import edu.esprit.GUI.admintablemodel;
import edu.esprit.entities.Admin;
import edu.esprit.util.Controle;
import javax.swing.JOptionPane;
import static sun.security.jgss.GSSUtil.login;

/**
 *
 * @author Abd
 */
public class ADMIN_paneladminprincipal extends javax.swing.JPanel {

    /**
     * Creates new form paneladminprincipal
     */
    public ADMIN_paneladminprincipal() {
        initComponents();
         nnnom.setVisible(false);
        nnprnom.setVisible(false);
        nnlogin.setVisible(false);
        nnmdp.setVisible(false);
        nnmail.setVisible(false);

       
        oknom.setVisible(false);
        okprnm.setVisible(false);
        oklogin.setVisible(false);
        okmdp.setVisible(false);
        okmail.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jp1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jp2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtprnom = new javax.swing.JTextField();
        txtmdp = new javax.swing.JTextField();
        txtlogin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtmail = new javax.swing.JTextField();
        nnnom = new javax.swing.JLabel();
        oknom = new javax.swing.JLabel();
        okprnm = new javax.swing.JLabel();
        nnprnom = new javax.swing.JLabel();
        nnmdp = new javax.swing.JLabel();
        okmdp = new javax.swing.JLabel();
        oklogin = new javax.swing.JLabel();
        nnlogin = new javax.swing.JLabel();
        nnmail = new javax.swing.JLabel();
        okmail = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jp3 = new javax.swing.JPanel();
        btnaj = new javax.swing.JButton();
        btnmod = new javax.swing.JButton();
        btnsup = new javax.swing.JButton();

        jp1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setModel(new admintablemodel());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1393467782_menu-24.png"))); // NOI18N
        jButton1.setText("Afficher tout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jp2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jp2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nom:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Login:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Prenom");

        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        txtnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomKeyTyped(evt);
            }
        });

        txtprnom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtprnomKeyTyped(evt);
            }
        });

        txtmdp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmdpKeyTyped(evt);
            }
        });

        txtlogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtloginKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Email");

        txtmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmailActionPerformed(evt);
            }
        });
        txtmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmailKeyTyped(evt);
            }
        });

        nnnom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N

        oknom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accept.png"))); // NOI18N

        okprnm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accept.png"))); // NOI18N

        nnprnom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N

        nnmdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N

        okmdp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accept.png"))); // NOI18N

        oklogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accept.png"))); // NOI18N

        nnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N

        nnmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/cross.png"))); // NOI18N

        okmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/accept.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Mot de passe:");

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(19, 19, 19)
                        .addComponent(txtmdp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nnmdp)
                            .addComponent(okmdp)))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(64, 64, 64)
                                .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(oknom)
                                    .addComponent(nnnom)))
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(47, 47, 47)
                                .addComponent(txtprnom, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nnprnom)
                                    .addComponent(okprnm)))
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7))
                                .addGap(58, 58, 58)
                                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp2Layout.createSequentialGroup()
                                        .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nnmail)
                                            .addComponent(okmail)))
                                    .addGroup(jp2Layout.createSequentialGroup()
                                        .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(oklogin)
                                            .addComponent(nnlogin))))))))
                .addGap(92, 92, 92))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(oknom)
                        .addComponent(nnnom))
                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)))
                .addGap(26, 26, 26)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nnprnom)
                        .addComponent(okprnm))
                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtprnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(26, 26, 26)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nnmdp)
                        .addComponent(okmdp))
                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtmdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(26, 26, 26)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(nnlogin, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(oklogin, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(nnmail)
                    .addComponent(okmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnaj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnaj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1393447771_plus-24.png"))); // NOI18N
        btnaj.setText("Ajouter");
        btnaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajActionPerformed(evt);
            }
        });

        btnmod.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnmod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1393462221_refresh.png"))); // NOI18N
        btnmod.setText("Modifier");
        btnmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodActionPerformed(evt);
            }
        });

        btnsup.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1393447726_cross-24.png"))); // NOI18N
        btnsup.setText("Supprimer");
        btnsup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsupMouseClicked(evt);
            }
        });
        btnsup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnmod)
                .addGap(18, 18, 18)
                .addComponent(btnsup)
                .addContainerGap())
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(443, 443, 443))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajActionPerformed
        // TODO add your handling code here:
        MenuAdmin m=new MenuAdmin();
        new Ajoutadmin(m, mdp).setVisible(true);

    }//GEN-LAST:event_btnajActionPerformed

    private void btnmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodActionPerformed
        // TODO add your handling code here:
        AdminDAO adDAO = new AdminDAO();
        Admin test = new Admin();

        if ((nom == false) || (prenom == false) || (email == false) || (login == false) || (mdp == false)) {
            jperr.showMessageDialog(jp3, "Certaines données saisies sont invalides", "Erreur", jperr.ERROR_MESSAGE);
        } else {
            int row =jTable1.getSelectedRow();
            String tableclick=(jTable1.getModel().getValueAt(row, 0).toString());
            int id=Integer.parseInt(tableclick);
            test.setId_admin(id);
            test.setNom(txtnom.getText());
            test.setPrenom(txtprnom.getText());
            test.setLogin(txtlogin.getText());
            test.setMdp(txtmdp.getText());
            test.setEmail(txtmail.getText());
            adDAO.updateAdmin(test);
           

        }
         jTable1.setModel(new admintablemodel());

    }//GEN-LAST:event_btnmodActionPerformed

    private void btnsupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsupMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsupMouseClicked

    private void btnsupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupActionPerformed
        // TODO add your handling code here:

        AdminDAO adDAO = new AdminDAO();
        Admin test = new Admin();
        int p=JOptionPane.showConfirmDialog
        (this, "Voulez vous vraiment supprimer le compte selectionné?", "Confimation", JOptionPane.YES_NO_OPTION );
        if(p==0){
            int row = jTable1.getSelectedRow();
            String tableclick = (jTable1.getModel().getValueAt(row, 0).toString());
            adDAO.deleteAdmin(Integer.parseInt(tableclick));
            jTable1.setModel(new admintablemodel());}
    }//GEN-LAST:event_btnsupActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomKeyTyped
        // TODO add your handling code here:
        Controle c = new Controle();
        boolean result = c.controlestring(txtnom.getText());
        System.out.println("" + result);
        if (result == true) {
            nom = true;
            oknom.setVisible(true);
            nnnom.setVisible(false);
        } else if (result == false) {
            nom = false;
            oknom.setVisible(false);
            nnnom.setVisible(true);
        } else if (txtnom.getText() == null) {
            nom = false;
            oknom.setVisible(false);
            nnnom.setVisible(true);
        }
    }//GEN-LAST:event_txtnomKeyTyped

    private void txtprnomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprnomKeyTyped
        // TODO add your handling code here:
        Controle c = new Controle();
        boolean result = c.controlestring(txtprnom.getText());
        System.out.println("" + result);
        if (result == true) {
            prenom = true;
            okprnm.setVisible(true);
            nnprnom.setVisible(false);
        } else if (result == false) {
            prenom = false;
            okprnm.setVisible(false);
            nnprnom.setVisible(true);
        } else if (txtprnom.getText() == null) {
            prenom = false;
            okprnm.setVisible(false);
            nnprnom.setVisible(true);
        }
    }//GEN-LAST:event_txtprnomKeyTyped

    private void txtmdpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmdpKeyTyped
        // TODO add your handling code here:
        Controle c = new Controle();
        boolean result = c.controlelogin(txtmdp.getText());
        System.out.println("" + result);
        if (result == true) {
            mdp = true;
            okmdp.setVisible(true);
            nnmdp.setVisible(false);
        } else if (result == false) {
            mdp = false;
            okmdp.setVisible(false);
            nnmdp.setVisible(true);
        } else if (txtmdp.getText() == null) {
            mdp = false;
            okmdp.setVisible(false);
            nnmdp.setVisible(true);
        }
    }//GEN-LAST:event_txtmdpKeyTyped

    private void txtloginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtloginKeyTyped
        // TODO add your handling code here:
        Controle c = new Controle();
        boolean result = c.controlelogin(txtlogin.getText());
        System.out.println("" + result);
        if (result == true) {
            login = true;
            oklogin.setVisible(true);
            nnlogin.setVisible(false);
        } else if (result == false) {
            login = false;
            oklogin.setVisible(false);
            nnlogin.setVisible(true);
        } else if (txtlogin.getText() == null) {
            login = false;
            oklogin.setVisible(false);
            nnlogin.setVisible(true);
        }
    }//GEN-LAST:event_txtloginKeyTyped

    private void txtmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmailActionPerformed

    private void txtmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmailKeyTyped
        // TODO add your handling code here:
        Controle c = new Controle();
        boolean result = c.controlemail(txtmail.getText());
        if (result == true) {
            email = true;
            okmail.setVisible(true);
            nnmail.setVisible(false);
        } else if (result == false) {
            email = false;
            okmail.setVisible(false);
            nnmail.setVisible(true);
        } else if (txtmail.getText() == null) {
            email = false;
            okmail.setVisible(false);
            nnmail.setVisible(true);
        }
    }//GEN-LAST:event_txtmailKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        AdminDAO adDAO = new AdminDAO();
        Admin test = new Admin();
        int row = jTable1.getSelectedRow();
        String tableclick = (jTable1.getModel().getValueAt(row, 0).toString());
        test = adDAO.findAdminById(Integer.parseInt(tableclick));

        txtprnom.setText(test.getPrenom());
        txtnom.setText(test.getNom());
        txtlogin.setText(test.getLogin());
        txtmdp.setText(test.getPrenom());
        txtmail.setText(test.getEmail());
        System.out.println("" + test.getId_admin());

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MenuAdmin m=new MenuAdmin();
        AdminAffichertout a=new AdminAffichertout(m, mdp);
        a.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaj;
    private javax.swing.JButton btnmod;
    private javax.swing.JButton btnsup;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JLabel nnlogin;
    private javax.swing.JLabel nnmail;
    private javax.swing.JLabel nnmdp;
    private javax.swing.JLabel nnnom;
    private javax.swing.JLabel nnprnom;
    private javax.swing.JLabel oklogin;
    private javax.swing.JLabel okmail;
    private javax.swing.JLabel okmdp;
    private javax.swing.JLabel oknom;
    private javax.swing.JLabel okprnm;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtmdp;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprnom;
    // End of variables declaration//GEN-END:variables
private javax.swing.JOptionPane jperr;
    public String message = "";
    public boolean nom = true;
    public boolean prenom = true;
    public boolean mdp = true;
    public boolean login = true;
    public boolean email = true;

}
